version: "3"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "8000:8080"
      - "443:443"
    environment:
      - VUE_APP_SHOTBOT_IP=${VUE_APP_SHOTBOT_IP}
      - VUE_APP_BACKEND_PORT=${VUE_APP_BACKEND_PORT}
      - VUE_APP_MAX_SHOTS=${VUE_APP_MAX_SHOTS}
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "${VUE_APP_BACKEND_PORT}:8080"
    restart: unless-stopped
    environment:
      - VUE_APP_SHOTBOT_IP=${VUE_APP_SHOTBOT_IP}
      - VUE_APP_BACKEND_PORT=${VUE_APP_BACKEND_PORT}
      - VUE_APP_MAX_SHOTS=${VUE_APP_MAX_SHOTS}
