version: "3"

volumes:
  redis-data:

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    environment:
      - VUE_APP_SHOTBOT_IP=${VUE_APP_SHOTBOT_IP}
      - VUE_APP_BACKEND_PORT=${VUE_APP_BACKEND_PORT}
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: 2
        max-size: 1m
    environment:
      - VUE_APP_SHOTBOT_IP=${VUE_APP_SHOTBOT_IP}
    depends_on:
      - redis
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    container_name: redis
    restart: unless-stopped
    volumes:
      - "./redis-data:/data"
    ports:
      - 6379:6379
    logging:
      driver: "json-file"
      options:
        max-file: 2
        max-size: 1m
