local_costmap:
  global_frame: "map"
  robot_base_frame: "base_footprint"

  update_frequency: 10.0
  publish_frequency: 5.0

  always_send_full_costmap: false

  transform_tolerance: 0.2

  rolling_window: true
  resolution: 0.05

  height: 3.0
  width: 3.0

  obstacle_layer:
    enabled:              true
    combination_method:   0
    track_unknown_space:  true    #true needed for disabling global path planning through unknown space
    obstacle_range: 5.0
    raytrace_range: 6.0
    inf_is_valid: false
    scan_filtered:
      sensor_frame: base_scan
      data_type: LaserScan
      topic: scan_filtered
      marking: true
      clearing: true
    observation_sources:  scan_filtered

  inflation_layer:
    enabled:              true
    cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius:     0.3

  plugins:
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
   #- {name: sonar_layer,         type: "range_sensor_layer::RangeSensorLayer"}

