scan_filter_chain:

- name: box
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: base_scan
    min_x: -0.32
    max_x: 0.31
    min_y: -0.26
    max_y: 0.26
    min_z: -1.0
    max_z: 1.0
    invert: false

- name: speckle_filter
  type: laser_filters/LaserScanSpeckleFilter
  params:
    filter_type: 0
    max_range: 1.0
    max_range_difference: 0.1
    filter_window: 2
