scan_filter_chain:

- name: box
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: base_scan
    min_x: -0.35
    max_x: 0.35
    min_y: -0.30
    max_y: 0.30
    min_z: -1.0
    max_z: 1.0
    invert: false
