global_costmap:
  global_frame: odom
  robot_base_frame: "base_footprint"

  update_frequency: 5.0
  publish_frequency: 2.0

  always_send_full_costmap: false

  resolution: 0.05

  static_layer:
    map_topic: /map
    subscribe_to_updates: true

  obstacle_layer:
    enabled:              true
    combination_method:   1
    track_unknown_space:  true    #true needed for disabling global path planning through unknown space
    obstacle_range: 5.0
    raytrace_range: 6.0
    inf_is_valid: false
    scan_filtered:
      sensor_frame: base_scan
      data_type: LaserScan
      topic: scan_filtered
      marking: true
      clearing: true
    observation_sources:  scan_filtered

  inflation_layer:
    enabled:              true
    cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius:     0.2

  plugins:
     - {name: static_layer, type: "costmap_2d::StaticLayer"}
     - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
     - {name: inflated_layer, type: "costmap_2d::InflationLayer"}

