footprint: [[-0.65, -0.30], [-0.65, 0.30], [0.05, 0.30], [0.05, -0.30]]

robot_base_frame: base_footprint
update_frequency: 30.0
publish_frequency: 20.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    enable: true
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    enabled: true
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: /scan_filtered, inf_is_valid: true}

inflation:
    enabled: true
    inflation_radius: 1.0

  
